name: Auto Format with autopep8

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ main, "**" ]

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install autopep8
        run: pip install autopep8

      - name: Run autopep8 formatting
        run: autopep8 --in-place --recursive .

      - name: Check for changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "chore: auto format Python code with autopep8"
            git push
          else
            echo "No formatting changes needed."
          fi
